### PR TITLE
Ensure lib folder is built before copying

### PR DESCRIPTION
**Pull request by web-padawan**
Cloned the repo and it failed on `postinstall` because of this.

### CODE REVIEW

**Comment by web-padawan** [comment]
@e111077 PTAL

**Comment by web-padawan** [comment]
@e111077 Thanks! 

BTW, can you clarify the plans regarding this repo? Are you going to continue working on it?

I noticed that there is a recent 0.1.0 release of [@codemirror/next](https://github.com/codemirror/codemirror.next). Will try it with `codemirror` branch.

**Comment by e111077** [comment]
This initially served as a plan for a serverless code editor for lit elements. The part we got hung up on was the actual text editor: monaco is too heavy, codemirror is too old, and codemirror.next was too new at the time (and syntax highlighter had not been matured for their next generation yet).

We do intend to look at this again, but it has been prioritized lower than SSR, and Material Components.  Currently don't have a timeline as to when we're going back to this. Essentially iceboxed for now

**Comment by e111077** [comment]
Oh and current status is that it is currently a bunch of experimental branches: e.g. codemirror 5, 6, monaco, and a stateless serviceworker. Still messy code 😬

**Pull request merged**
